### ISSUE TITLE
Feature request: disabled form input

### ISSUE THREAD

**Issue by mottox2** [bmcmahen/sancho#15]
Hi. I think sancho is great design system. Thank you.
I want disabled form components. 

Shoud I send a pull request? or I wait a release?

**Comment by bmcmahen** [comment]
OMG how'd I miss that? I'll do that today and post a new release. Thanks for letting me know.

**Comment by bmcmahen** [comment]
Fixed disabled states and added slightly nicer error states, too. Will post a new release soonish (next day or so)

<img width="341" alt="Screen Shot 2019-05-08 at 8 43 17 PM" src="https://user-images.githubusercontent.com/1236841/57425971-4bc84e00-71d2-11e9-955f-340453ad7cac.png">

**Comment by bmcmahen** [comment]
Changes available in 3.1.0.

**Comment by mottox2** [comment]
Great thanks! I upgrade to 3.1.0.
