### ISSUE TITLE
I have a idea about content display for 

### ISSUE THREAD

**Issue by heerzhang** [bmcmahen/sancho#43]
HI bmcmahen。 In my scenario，now use PDF template files to build reports, but it‘s inconvenient when the template have to change because of page is fixing。I think use web to replace pdf files，just as  A4  paper with fixed xy sizes in contrast of scrollable screens。But in printer UI use case，how the web DOM object can know which page number it`s in。And how to preserve the unity of something just like picture or table row or other inseparable DOM, in such case , must leave gaps and start a new page。Besides, I want to fixed position some DOM at a certain number page, even or odd number of pages of the web when print preview, or auo-calculated page number just as catalog of a book。

**Comment by bmcmahen** [comment]
Hrmm, sorry. Not sure I follow really. Maybe write it in your original language and convert it using something like google translate?

**Comment by heerzhang** [comment]
When we print, how can I know which page number the current label is in?

**Comment by bmcmahen** [comment]
Hrmm, this seems unrelated to sancho itself, so I'm going to close for now.

**Comment by heerzhang** [comment]
I have to copy sancho and rename to other and publish as a npm packge。 Because I can not link sancho Locally, use sancho as a local Link will throw:Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:1 2 3. You might have more than one copy of React in the same app

**Comment by heerzhang** [comment]
I will copy sancho and rename to "   customize-easy-UI-component    " and publish as a npm packge of https://www.npmjs.com/。
