### ISSUE TITLE
Emotion illegal escape sequence error/warning

### ISSUE THREAD

**Issue by apolzon** [bmcmahen/sancho#47]
I recently upgraded some dependencies in order to get the emotion babel plugin + preset working correctly, and emotion is now emitting many dev errors due to illegal escape sequences which seem to be coming from various Sancho components:

`You have illegal escape sequence in your template literal, most likely inside content's property value.
Because you write your CSS inside a JavaScript string you actually have to do double escaping, so for example "content: '\00d7';" should become "content: '\\00d7';".
You can read more about this here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#ES2018_revision_of_illegal_escape_sequences`

More info on the emotion commit where I believe this warning was added: https://github.com/emotion-js/emotion/commit/66cda64128631790b81e3c9df273a972358ea593?diff=unified

I could definitely be wrong and this error could have a root cause somewhere besides Sancho, but the error/warning was being thrown by various Sancho components (Breadcrumbs, Toast, Tabs to name a few) on the line near the beginning of the file where the hideScrollbar variable is defined. (ie, in the esm output, Breadcrumbs.js line 14)

Looking at your typescript source where that variable is defined, I'm not totally convinced the issue is actually with Sancho, but I'll go ahead and leave this here in case anyone has run into this and knows what the issue is.

Thanks.

**Comment by apolzon** [comment]
I haven't used typescript, so I don't know a lot of the intricacies, but after hacking away at source code and debugging for a bit, it seems that when assigning a css literal to a variable (ie `const foo = css```), the typescript compiler is erroneously interpreting that as a template literal which causes the arguments sent to emotion to serialize the css strings to get an argument that doesn't quite conform to what they expect. (Specifically, an object that looks like an array, but has keys of 0 and raw instead of 0 and 1).

So, my hunch is there's some sort of order of operations issue with typescript + the emotion css pragma.

I did find this which seems like it may be related: https://github.com/emotion-js/emotion/issues/1046.

Alternatively, the couple places I saw you assigning a css literal to a variable they were only being used once, so if you inlined that usage I think the problem would go away.

**Comment by bmcmahen** [comment]
hey @apolzon . Thanks for the detailed report. 

I haven't actually used the emotion babel plugin, so I haven't noticed this issue myself. Are you able to try inlining the usage to see if the error goes away? Either that, or setup a minimal reproduction that I could easily clone and test myself?

**Comment by apolzon** [comment]
Yeah, disabling the babel preset gets rid of the error. I’ll try to put together a small reproduction repo this weekend. Thanks.

**Comment by apolzon** [comment]
Well this was completely unexpected -- as it turns out, using a babel.config.js file instead of .babelrc or .babelrc.js or package.json config is what causes the issue.

If you're curious, here's the repo I setup that reproduces the error: https://github.com/apolzon/sancho-emotion-preset-debug (there's a second branch using .babelrc.js that works fine)

I have no clue what the difference introduced could be with using the config.js option, but at least I know to avoid it for now. Sorry for wasting your time, and thanks for the quick response!

**Comment by bmcmahen** [comment]
That's an odd one! Glad you figured it out.
