### ISSUE TITLE
Do you need assistance with prop documentation?

### ISSUE THREAD

**Issue by f1yn** [bmcmahen/sancho#52]
Hey, I'm currently working on building my own starter app around Sancho's components, and was curious if you needed help mapping out various component props in your documentation?

I'm finding myself often reading through the component definitions to figure out what props to use - which is fine, but my goto is the docs.

**Comment by bmcmahen** [comment]
Sure - any documentation help would be great. The props are supposed to be automatically generated, but it's not always very reliable.
